Repository yuyangJin/PerFlow-AI, pull requests merged in 2025-03, with the labels that each got.

#59 [Feat] #24 Update class PipeCostConfig and related classes to support imbalanced partition
  perflowai/parallel/pipeline_parallel/__init__.py
  perflowai/parallel/pipeline_parallel/ppgraph.py
  perflowai/parallel/pipeline_parallel/zerobubble.py
  tests/integration_tests/imbalanced_pipeline_visualize_test.py
  tests/units_tests/PipeCostConfig_test.py
Labels: enhancement

#62 [Refactor] #61 Absolute path to relative path
  perflowai/core/__init__.py
  perflowai/core/trace.py
  perflowai/parallel/__init__.py
  perflowai/parallel/data_parallel.py
  perflowai/parallel/pipeline_parallel/__init__.py
  perflowai/parallel/pipeline_parallel/gpipe.py
  perflowai/parallel/pipeline_parallel/interleaved1f1b.py
  perflowai/parallel/pipeline_parallel/pipedream.py
  perflowai/parallel/pipeline_parallel/ppgraph.py
  perflowai/parallel/pipeline_parallel/zerobubble.py
  perflowai/parallel/tensor_parallel.py
  perflowai/reader/nsys_reader.py
  perflowai/reader/reader.py
  perflowai/reader/torchprofiler_reader.py
  perflowai/simulator/__init__.py
  perflowai/simulator/comm_simulator.py
  perflowai/simulator/dptp_simulator.py
  perflowai/simulator/oprt_simulator.py
  perflowai/simulator/pp_simulator.py
  perflowai/simulator/simulator.py
  perflowai/trace_op/__init__.py
  perflowai/trace_op/filter.py
  perflowai/trace_op/merge.py
  perflowai/visualizer/__init__.py
  perflowai/visualizer/memfootprint_visualizer.py
  perflowai/visualizer/trace_visualizer.py
  perflowai/workflow/__init__.py
  tests/integration_tests/gpipe_simulate_visualize_test.py
  tests/integration_tests/heterogeneous_simulate_visualize_test.py
  tests/integration_tests/imbalanced_pipeline_visualize_test.py
  tests/integration_tests/interleaved1f1b_simulate_visualize_test.py
  tests/integration_tests/memory_footprint_test.py
  tests/integration_tests/pipedream_simulate_visualize_test.py
  tests/integration_tests/visualize_json_test.py
  tests/integration_tests/zbv_simulate_visualize_test.py
  tests/integration_tests/zerobubble_simulate_visualize_test.py
  tests/units_tests/Event_test.py
  tests/units_tests/FwdBwdEvent_test.py
  tests/units_tests/GPipeGraph_test.py
  tests/units_tests/Interleaved1F1BGraph_test.py
  tests/units_tests/PipeCostConfig_test.py
  tests/units_tests/PipeDreamGraph_test.py
  tests/units_tests/TorchProfilerTraceReader_test.py
  tests/units_tests/ZeroBubbleGraph_test.py
  tests/units_tests/filter_test.py
  tests/units_tests/flowgraph_test.py
  tests/units_tests/flownode_test.py
  tests/units_tests/merge_test.py
  tests/units_tests/pipepartitionconfig_test.py
  tests/units_tests/ppgraph_test.py
  tests/units_tests/ppsimulator_test.py
  tests/units_tests/trace_test.py
Labels: enhancement

#64 [Refactor] #61 Uppercase the file name of tests
  tests/units_tests/Filter_test.py
  tests/units_tests/FlowGraph_test.py
  tests/units_tests/FlowNode_test.py
  tests/units_tests/Merge_test.py
  tests/units_tests/PPGraph_test.py
  tests/units_tests/PipePartitionConfig_test.py
  tests/units_tests/Trace_test.py
Labels: enhancement

#65 [Feat] #52 Update OffReLoadEvent class, some functions are not added or implemented yet and will be refined when it is necessary.
  perflowai/core/__init__.py
  perflowai/core/event.py
  tests/units_tests/OnReLoadEvent_test.py
Labels: enhancement

#67 [Feat] #53 Update class PPSimulator to support simulation on different resource (CPU, GPU, PCIE, etc.)
  perflowai/core/__init__.py
  perflowai/core/event.py
  perflowai/parallel/pipeline_parallel/__init__.py
  perflowai/parallel/pipeline_parallel/interleaved1f1b.py
  perflowai/parallel/pipeline_parallel/ppgraph.py
  perflowai/simulator/pp_simulator.py
  tests/units_tests/OffReLoadEvent_test.py
  tests/units_tests/PipeOffloadConfig_test.py
Labels: enhancement

#69 [Feat] #68 Update TraceVisiualizer class, support offload_config
  perflowai/visualizer/trace_visualizer.py
  tests/integration_tests/interleaved1f1b_simulate_visualize_test.py
Labels: enhancement

#71 [Bugfix] #70 Add check for the result of __compute_mb_and_chk
  perflowai/parallel/pipeline_parallel/interleaved1f1b.py
Labels: bug

#74 [Refactor] #72 Reconstruct the simulator module and update the UML file
  docs/PerFlow-AI.plantuml
  perflowai/simulator/__init__.py
  perflowai/simulator/comm/__init__.py
  perflowai/simulator/comm/comm_simulator.py
  perflowai/simulator/dptp/__init__.py
  perflowai/simulator/dptp/dptp_simulator.py
  perflowai/simulator/mem/__init__.py
  perflowai/simulator/mem/mem_simluator.py
  perflowai/simulator/oprt/__init__.py
  perflowai/simulator/oprt/oprt_simulator.py
  perflowai/simulator/pipeline/__init__.py
  perflowai/simulator/pipeline/pp_simulator.py
Labels: documentation

#75 [Bugfux] #72 Fix the typos and import bug
  perflowai/parallel/pipeline_parallel/__init__.py
  perflowai/simulator/__init__.py
  perflowai/simulator/dptp/dptp_simulator.py
  perflowai/simulator/pipeline/__init__.py
  perflowai/simulator/pipeline/pp_simulator.py
Labels: bug

#76 [Feat] #55 Add a recompute feature in the FwdBwdEvent class
  perflowai/core/event.py
  perflowai/parallel/pipeline_parallel/ppgraph.py
  tests/units_tests/PipeRecomputeConfig_test.py
Labels: enhancement

#78 [Feat] #77 Update the PipeCostConfig class to support chunk-level partition (list of list)
  perflowai/parallel/pipeline_parallel/ppgraph.py
  perflowai/parallel/pipeline_parallel/zerobubble.py
  tests/units_tests/PipeCostConfig_test.py
Labels: enhancement

#84 [Bugfix] #83 Complete the missing parts of Inter-stage F dependence
  perflowai/parallel/pipeline_parallel/interleaved1f1b.py
Labels: bug

#80 [Feat] #79 Update the PipeOffloadConfig class to support chunk-level partition (list of list)
  perflowai/parallel/pipeline_parallel/interleaved1f1b.py
  tests/units_tests/PipeOffloadConfig_test.py
Labels: enhancement

#86 [Feat] #85 Update the MemoryFootprintVisualizer & TraceVisiualizer class to support receiving a base value & printing the overall results
  perflowai/visualizer/memfootprint_visualizer.py
  perflowai/visualizer/trace_visualizer.py
Labels: enhancement

#87 [Test] #54 Update some classes, support memory footprint for offloading
  perflowai/core/event.py
  perflowai/parallel/pipeline_parallel/interleaved1f1b.py
  perflowai/parallel/pipeline_parallel/ppgraph.py
  tests/units_tests/OffReLoadEvent_test.py
Labels: enhancement
